# conda env create -f environment.yml
# conda env update --file environment.yml --prune

name: astrosort
dependencies:
  - python=3.12
  - pandas=2.2.3
  - astroquery=0.4.9
  - libpython-static=3.12.9
  - pip
  - pip:
      - PyExifTool==0.5.6
      - PySide6==6.8.2.1